name: Automatic Gym class booking

on:
  schedule:
    - cron: '1 19 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script gym_class_booking.py
        env:
          creds: ${{ secrets.CREDS }}
          captcha_api_key: ${{ secrets.CAPTCHA_API_KEY }}
        run: python gym_class_booking.py
